window.timelineItems = [
      /* Paste your entire array here */
      {
        date: '2700s BCE',
        location: 'China',
        title: 'Silk Production and Trade',
        description: 'Chinese silk becomes a prized lightweight...',
        img: 'img/silk.jpg',
        people: ['Legendary Empress Leizu (mythical)'],
        category: 'Conceptual & Scientific Breakthroughs',
        connections: [
          "Early Kites", 
          "Bartolomeu de Gusmão\'s Passarola", 
          "Montgolfier Brothers' Hot Air Balloon",
          "Henri Giffard\'s Dirigible",
          "Charles Renard and Arthur Constantin\'s Le France",
        ],
        row: 1
      },
  {
    date: '100s BCE',
    location: 'China',
    title: 'Paper Production and Trade',
    description: 'Paper is invented in China and then spreads to the Arabic world in the 700s BC, then to Medieval Europe. A key material innovation that aided future flight experiments. The lightweight material was later used in hot air lanterns in China. Even later, Leonardo da Vinci and George Cayley used paper and other lightweight materials to create models and test their theories of flight ',
    img: "/api/placeholder/100/100",
    people: ['Mozi', 'Lu Ban'],
    category: 'Conceptual & Scientific Breakthroughs',
    row: 1,
    connections: ['Early Kites', 'Kongming\'s Sky Lantern', 'Leonardo da Vinci\'s Flying Machines']
  },
  {
    date: '500s BCE',
    location: 'China',
    title: 'Early Kites',
    description: 'Kites are invented in China, an early form of human flight.',
    img: "/api/placeholder/100/100",
    people: ['Mozi', 'Lu Ban'],
    category: 'Engineering Experiments & Demonstrations',
    row: 1,
    connections: ['Paper Production and Trade']
  },
      {
        date: '500s BCE',
        location: 'India',
        title: 'The Pushpaka Vimana',
        description: 'A mythical self-moving aerial vehicle described in the Ramayana epic; one of the earliest stories featuring a ‘flying machine.’',
        img: "/api/placeholder/100/100",
        people: ['The Pushpaka Vimana'],
        category: 'Sociocultural Factors',
        row: 1,
        connections: ['Abbas Ibn Firnas\'s jump', 'Eilmer of Malmesbury\'s jump', 'João Torto\'s Failed Flight Attempt' ]
      },
    {
        date: '500s BCE',
        location: 'Greece',
        title: 'The Myth of Icarus and Daedalus',
        description: 'This myth, often depicted in classical art and referenced by poets and playwrights, is one of the earliest and most enduring symbols of humanity’s flight aspirations—and of hubris. It reminds us that the dream of flying dates back to antiquity and has long carried both awe and cautionary overtones.',
        img: "/api/placeholder/100/100",
        people: ['The Myth of Icarus and Daedalus'],
        category: 'Sociocultural Factors',
        row: 1,
        connections: ['Abbas Ibn Firnas\'s jump', 'Eilmer of Malmesbury\'s jump', 'João Torto\'s Failed Flight Attempt' ]
      },
  {
        date: '400s BCE',
        location: 'Tarentum, Italy',
        title: 'Archytas\' Flying Pigeon',
        description: 'Archytas of Tarentum creates a wooden pigeon that could "fly" using a jet of air.',
        img: "/api/placeholder/100/100",
        people: ['Archytas of Tarentum'],
        category: 'Engineering Experiments & Demonstrations',
        row: 1,
        connections: ['The Myth of Icarus and Daedalus']
      },
      {
        date: '200s BCE',
        location: 'Syracuse, Sicily',
        title: 'Archimedes\' Buoyancy Principle',
        description: 'Archimedes discovers the principles of buoyancy, which later influence theories of flight.',
        img: "/api/placeholder/100/100",
        people: ['Archimedes'],
        category: 'Conceptual & Scientific Breakthroughs',
        row: 1,
        connections: ['Roger Bacon\'s Air Support Theory', 'Robert Hooke\'s Airflow']
      },
   {
        date: '200s BCE',
        location: 'China',
        title: 'Kongming\'s Sky Lantern',
        description: 'Kongming invents the sky lantern, the first hot air balloon. From its military use, it became known as the Kongming lantern.',
        img: "/api/placeholder/100/100",
        people: ['Kongming'],
        category: 'Engineering Experiments & Demonstrations',
        row: 1,
     connections: ['Early Kites', 'Paper Production and Trade']
      },
    {
    date: '100s',
    location: 'Alexandria, Egypt',
    title: 'Hero\'s Aeolipile',
    description: 'Hero of Alexandria designs the aeolipile, a simple steam turbine. While not used for flight, it demonstrated the potential of steam power.',
    img: "/api/placeholder/100/100",
    people: ['Hero of Alexandria'],
    category: 'Engineering Experiments & Demonstrations',
    row: 1,
      connections: ['Archytas\' Flying Pigeon', 'Henri Giffard\'s Dirigible']
  },
      {
        date: '800s',
        location: 'Spain',
        title: 'Abbas Ibn Firnas\'s jump',
        description: 'Abbas Ibn Firnas jumps from a tower wearing a cloak stiffened with wooden struts. He survives but is injured—an early documented instance of someone attempting to break their fall using (crude) aerodynamic principles.',
        img: "/api/placeholder/100/100",
        people: ['Abbas Ibn Firnas'],
        category: 'Engineering Experiments & Demonstrations',
        row: 2,
        connections: ['The Myth of Icarus and Daedalus', 'Eilmer of Malmesbury\'s jump', 'João Torto\'s Failed Flight Attempt']
      },
        {
        date: '800s',
        location: 'Middle East and India',
        title: 'The Ebony Horse Tale',
        description: 'One of the tales from One Thousand and One Night. An inventor presents a magical mechanical horse to a Persian king; the horse can fly its rider into the sky.',
        img: "/api/placeholder/100/100",
        people: ['The Ebony Horse'],
        category: 'Sociocultural Factors',
        row: 2,
        connections: ['Abbas Ibn Firnas\'s jump', 'Eilmer of Malmesbury\'s jump', 'João Torto\'s Failed Flight Attempt'] // No connections here.
      },
    {
    date: '900s',
    location: 'China',
    title: 'Gunpowder Invention',
    description: 'Invented in China for fireworks and warfare, gunpowder also sowed the seed for rocketry, influencing the concept of thrust and controlled explosions for propulsion.',
    img: '/api/placeholder/100/100',
    people: ['Chinese Alchemists'],
    category: 'Conceptual & Scientific Breakthroughs',
    connections: [],
    row: 2
  },
  {
        date: '1000s',
        location: 'England',
        title: 'Eilmer of Malmesbury\'s jump',
        description: 'A Benedictine monk who tries to fly with a glider-like apparatus. He may have glided a short distance from a tower before crashing. Despite the failure, he allegedly recognized that a tail or tailplane might have provided stability.',
        img: "/api/placeholder/100/100",
        people: ['Eilmer of Malmesbury'],
        category: 'Engineering Experiments & Demonstrations',
        row: 2,
        connections: ['The Myth of Icarus and Daedalus', 'Abbas Ibn Firnas\'s jump', 'João Torto\'s Failed Flight Attempt']
      },
      {
        date: '1290s',
        location: 'England',
        title: 'Roger Bacon\'s Air Support Theory',
        description: 'Roger Bacon theorizes that air can support objects like water supports boats.',
        img: "/api/placeholder/100/100",
        people: ['Roger Bacon'],
        category: 'Conceptual & Scientific Breakthroughs',
        row: 2,
        connections: ['Archimedes\' Buoyancy Principle', 'Robert Hooke\'s Airflow']
      },
    {
    date: '1440s',
    location: 'Mainz, Germany',
    title: 'Gutenberg\'s Printing Press',
    description: 'Johannes Gutenberg develops the movable-type printing press, drastically speeding the circulation of new ideas and scientific works, including theories of flight.',
    img: '/api/placeholder/100/100',
    people: ['Johannes Gutenberg'],
    category: 'Conceptual & Scientific Breakthroughs',
    connections: ['Paper Production and Trade'],
    row: 2
  },
      {
        date: '1480s',
        location: 'Italy',
        title: 'Leonardo da Vinci\'s Flying Machines',
        description: "Leonardo da Vinci sketches various flying machines, including an ornithopter and a precursor to the helicopter.",
        img: "/api/placeholder/100/100",
        people: ['Leonardo da Vinci'],
        category: 'Sociocultural Factors',
        row: 2,
        connections: ['Paper Production and Trade']
      },
      {
        date: '1540s',
        location: 'Portugal',
        title: 'João Torto\'s Failed Flight Attempt',
        description: 'João Torto, a Portuguese barber, attempts human flight with fabric wings but falls to his death.',
        img: "/api/placeholder/100/100",
        people: ['João Torto'],
        category: 'Engineering Experiments & Demonstrations',
        row: 2,
        connections: ['The Myth of Icarus and Daedalus', 'Abbas Ibn Firnas\'s jump', 'Eilmer of Malmesbury\'s jump', 'João Torto\'s Failed Flight Attempt']
      },
  {
  date: '17th–19th Centuries',
  location: 'Europe',
  title: 'The Gentleman Scientist Tradition',
  description: 'Wealthy or well-connected amateurs (often aristocrats) pursued scientific research as a leisure activity, self-funding experiments without needing immediate commercial return. Figures like Sir George Cayley (an English baronet) exemplify this ethos; their private means allowed them to freely investigate aerodynamics, laying crucial groundwork for later practical aviation breakthroughs.',
  img: '/api/placeholder/100/100',
  people: ['Sir George Cayley'],
  category: 'Sociocultural Factors',
  connections: [],
  row: 2
},
    {
        date: '1634',
        location: 'Holy Roman Empire',
        title: 'Kepler\'s Somnium',
        description: 'One of the first “proto–science fiction” works. A fictional narrative describing a journey to the Moon, introducing early ideas on celestial mechanics. A text showing flight/space travel in a quasi-scientific way.',
        img: "/api/placeholder/100/100",
        people: ['Johannes Kepler'],
        category: 'Sociocultural Factors',
        row: 2,
        connections: [] // No connections here.
      },
      {
        date: '1638',
        location: 'England',
        title: 'Francis Godwin\'s The Man in the Moone',
        description: 'One of the first “proto–science fiction” works. A utopian story describing lunar travel using large, trained birds; an early example of flight-themed fiction and speculation.',
        img: "/api/placeholder/100/100",
        people: ['Francis Godwin'],
        category: 'Sociocultural Factors',
        row: 2,
        connections: [] // No connections here.
      },
  {
        date: '1657',
        location: 'France',
        title: 'Cyrano de Bergerac\'s Comical History of the States and Empires of the Moon',
        description: 'One of the first “proto–science fiction” works. Although comedic, it proposed mechanical means of leaving Earth, bridging mythic flight and more scientifically grounded speculation.',
        img: "/api/placeholder/100/100",
        people: ['Cyrano de Bergerac'],
        category: 'Sociocultural Factors',
        row: 2,
        connections: [] // No connections here.
      },
        {
        date: '1659',
        location: 'England',
        title: 'Robert Hooke\'s Airflow',
        description: 'Robert Hooke investigates concepts of drag and airflow, contributing to the body of knowledge that would eventually be applied to flight.',
        img: "/api/placeholder/100/100",
        people: ['Robert Hooke'],
        category: 'Conceptual & Scientific Breakthroughs',
        row: 2,
        connections: ['Archimedes\' Buoyancy Principle', 'Roger Bacon\'s Air Support Theory'] // No connections here.
      },
      {
        date: '1687',
        location: 'England',
        title: 'Newton\'s Laws of Motion',
        description: 'Lays out the three laws of motion and universal gravitation, essential to understanding how and why aircraft can generate lift and react to forces in flight.',
        img: "/api/placeholder/100/100",
        people: ['Isaac Newton'],
        category: 'Conceptual & Scientific Breakthroughs',
        row: 2,
        connections: [] // No connections here.
      },
      {
        date: '1709',
        location: 'Portugal',
        title: 'Bartolomeu de Gusmão\'s Passarola',
        description: 'Bartolomeu de Gusmão, a Brazilian-Portuguese priest, demonstrates a hot air balloon prototype called the "Passarola."',
        img: "/api/placeholder/100/100",
        people: ['Bartolomeu de Gusmão'],
        category: 'Engineering Experiments & Demonstrations',
        row: 3,
        connections: ['Kongming\'s Sky Lantern', 'Archimedes\' Buoyancy Principle']
      },
        {
        date: '1726',
        location: 'England',
        title: 'Jonathan Swift\'s Flying Island of Laputa',
        description: 'Though satire, Laputa symbolizes the human longing to master flight and the sky—exaggerated to the point of political power (the island hovers over other lands). It predates real scientific progress but demonstrates how flight was becoming embedded in broader cultural and sociopolitical thought.',
        img: "/api/placeholder/100/100",
        people: ['Jonathan Swift'],
        category: 'Sociocultural Factors',
        row: 3,
        connections: [] // No connections here.
      },
      {
        date: '1738',
        location: 'Switzerland/Netherlands',
        title: 'Daniel Bernoulli\'s Hydrodynamica',
        description: 'Describes how pressure in a moving fluid decreases as velocity increases; foundational for many aerodynamic analyses of wing lift.',
        img: "/api/placeholder/100/100",
        people: ['Daniel Bernoulli'],
        category: 'Conceptual & Scientific Breakthroughs',
        row: 3,
        connections: [] // No connections here.
      },
    {
    date: '1760–1840',
    location: 'Great Britain',
    title: 'Industrial Revolution',
    description: 'Steam power revolutionizes manufacturing and metallurgy, providing mass production methods and mechanical expertise that future aircraft builders would rely on.',
    img: '/api/placeholder/100/100',
    people: ['James Watt', 'Matthew Boulton'],
    category: 'Conceptual & Scientific Breakthroughs',
    connections: ['Hero\'s Aeolipile'],
    row: 3
  },
      {
        date: '1783',
        location: 'France',
        title: 'Montgolfier Brothers\' Hot Air Balloon',
        description: 'Jean-François Pilâtre de Rozier and François Laurent d\'Arlandes make the first manned flight in a hot air balloon built by the Montgolfier brothers.',
        img: "/api/placeholder/100/100",
        people: ['Jean-François Pilâtre de Rozier', 'François Laurent d\'Arlandes', 'Joseph-Michel Montgolfier', 'Jacques-Étienne Montgolfier'],
        row: 4,
        category: 'Engineering Experiments & Demonstrations',
        connections: ['Kongming\'s Sky Lantern'] 
      },
      {
  date: '1799',
  location: 'England',
  title: "George Cayley\'s Glider Design",
  description: "George Cayley designs the first modern glider with distinct lift, thrust, and control components.",
  img: "/api/placeholder/100/100",
  people: ['George Cayley'],
  row: 4,
  connections: ['Early Kites'],
  category: "Conceptual & Scientific Breakthroughs"
},
    {
    date: '1839',
    location: 'United States',
    title: 'Goodyear\'s Vulcanization of Rubber',
    description: 'Charles Goodyear discovers how to vulcanize rubber, producing stronger, more elastic material. Critical for balloon seals, early tires, and vibration-damping in aircraft.',
    img: '/api/placeholder/100/100',
    people: ['Charles Goodyear'],
    category: 'Conceptual & Scientific Breakthroughs',
    connections: ['Industrial Revolution'],
    row: 4
  },
  {
    date: '1851',
    location: 'London, England',
    title: 'The Great Exhibition',
    description: 'An international fair showcasing industrial inventions. Events like this spurred global interest in new machines, including early flying contraptions, by awarding prizes and attracting wealthy backers.',
    img: '/api/placeholder/100/100',
    people: ['Prince Albert', 'Henry Cole'],
    category: 'Sociocultural Factors',
    connections: ['Industrial Revolution'],
    row: 4
  },
{
  date: '1852',
  location: 'France',
  title: "Henri Giffard\'s Dirigible",
  description: "Henri Giffard invents the first controllable dirigible powered by a steam engine.",
  img: "/api/placeholder/100/100",
  people: ['Henri Giffard'],
  row: 5,
  connections: ['Hero\'s Aeolipile'],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1843',
  location: 'England',
  title: "William Henson\'s Aircraft Design",
  description: "William Henson patents an early aircraft design with fixed wings and a steam-powered engine.",
  img: "/api/placeholder/100/100",
  people: ['William Henson'],
  row: 6,
  connections: ['Hero\'s Aeolipile'],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1853',
  location: 'England',
  title: "George Cayley\'s Manned Glider Flight",
  description: "George Cayley successfully flies the first manned glider. Developed principles of lift, drag, and fixed-wing aircraft.",
  img: "/api/placeholder/100/100",
  people: ['George Cayley'],
  row: 7,
  connections: ['George Cayley\'s Glider Design'],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1865-1904',
  location: 'England',
  title: "Jules Verne\'s Novels",
  description: "Verne’s meticulous detail and semi-scientific style enthralled readers. He envisioned airships and cannon-propelled moonshots, inspiring generations of inventors to consider powered flight and eventual space travel.",
  img: "/api/placeholder/100/100",
  people: ['Jules Verne'],
  row: 7,
  connections: [],
  category: "Sociocultural Factors"
},
{
  date: '1871',
  location: 'England',
  title: "Francis Wenham\'s Wind Tunnel",
  description: "Francis Wenham builds the first wind tunnel to study aerodynamics. Proved that long, narrow wings generate more lift.",
  img: "/api/placeholder/100/100",
  people: ['Francis Wenham'],
  row: 7,
  connections: [],
  category: "Conceptual & Scientific Breakthroughs"
},
{
  date: '1884',
  location: 'France',
  title: "Charles Renard and Arthur Constantin\'s Le France",
  description: "Charles Renard and Arthur Constantin Krebs launch a non-rigid airship that inspires Zeppelin.",
  img: "/api/placeholder/100/100",
  people: ['Charles Renard', 'Arthur Constantin Krebs'],
  row: 7,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
  {
    date: '1885',
    location: 'Coventry, England',
    title: 'Safety Bicycle Revolution',
    description: 'John Kemp Starley produces the “safety bicycle.” This sparks a bicycle boom, driving advances in lightweight metal frames, gears, and precision machining—skills crucial for early airplane builders.',
    img: '/api/placeholder/100/100',
    people: ['John Kemp Starley'],
    category: 'Engineering Experiments & Demonstrations',
    connections: [],
    row: 7
  },
  {
    date: '1886',
    location: 'United States/France',
    title: 'Hall–Héroult Process for Aluminum',
    description: 'Charles Martin Hall and Paul Héroult separately discover a cost-effective method to produce aluminum, introducing a strong, lightweight metal for aircraft structures.',
    img: '/api/placeholder/100/100',
    people: ['Charles Martin Hall', 'Paul Héroult'],
    category: 'Conceptual & Scientific Breakthroughs',
    connections: ['Industrial Revolution'],
    row: 7
  },
{
  date: '1891',
  location: 'Germany',
  title: "Otto Lilienthal\'s Glider Flights",
  description: "Otto Lilienthal achieves controlled glider flights and documents aerodynamic research, proving human flight was possible.",
  img: "/api/placeholder/100/100",
  people: ['Otto Lilienthal'],
  row: 7,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1896',
  location: 'United States',
  title: "Octave Chanute\'s Biplane Glider",
  description: "Octave Chanute advances glider designs and builds a successful biplane glider, improving aviation theories.",
  img: "/api/placeholder/100/100",
  people: ['Octave Chanute'],
  row: 7,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1890',
  location: 'France',
  title: "Clément Ader\'s Éole",
  description: "Clément Ader builds the Éole, a bat-like steam-powered aircraft, which briefly lifts off but lacks control.",
  img: "/api/placeholder/100/100",
  people: ['Clément Ader'],
  row: 8,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1894',
  location: 'United States/United Kingdom',
  title: "Hiram Maxim\'s Steam-Powered Biplane",
  description: "Hiram Maxim builds and tests a massive steam-powered biplane but fails to achieve sustained flight.",
  img: "/api/placeholder/100/100",
  people: ['Hiram Maxim'],
  row: 8,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1896',
  location: 'United States',
  title: "Samuel Pierpont Langley\'s Aerodrome",
  description: "Samuel Pierpont Langley flies small, unmanned models successfully. Built the Aerodrome A, which failed at full scale.",
  img: "/api/placeholder/100/100",
  people: ['Samuel Pierpont Langley'],
  row: 8,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1899',
  location: 'United Kingdom',
  title: "Percy Pilcher\'s Powered Aircraft Design",
  description: "Percy Pilcher designs a powered aircraft but dies in a glider accident before testing it.",
  img: "/api/placeholder/100/100",
  people: ['Percy Pilcher'],
  row: 9,
  connections: [],
  category: "Conceptual & Scientific Breakthroughs"
},
{
  date: '1900',
  location: 'Germany',
  title: "Ferdinand von Zeppelin\'s Rigid Airships",
  description: "Ferdinand von Zeppelin develops rigid airships, leading to widespread use of zeppelins.",
  img: "/api/placeholder/100/100",
  people: ['Ferdinand von Zeppelin'],
  row: 9,
  connections: ['Hall–Héroult Process for Aluminum', 'Charles Renard and Arthur Constantin\'s Le France'],
  category: "Engineering Experiments & Demonstrations"
},
    {
    date: '1901',
    location: 'France',
    title: 'Deutsch de la Meurthe Prize',
    description: 'Industrialist Henri Deutsch de la Meurthe offers prizes for airship and airplane feats, sparking fierce competition. These contests push the development of powered flight in Europe.',
    img: '/api/placeholder/100/100',
    people: ['Henri Deutsch de la Meurthe'],
    category: 'Sociocultural Factors',
    connections: [],
    row: 9
  },
{
  date: '1901',
  location: 'United States',
  title: "Gustave Whitehead\'s Reported Flight",
  description: "Gustave Whitehead reportedly flies in Connecticut, though documentation remains debated.",
  img: "/api/placeholder/100/100",
  people: ['Gustave Whitehead'],
  row: 9,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1902',
  location: 'France',
  title: "Georges Méliès\'s A Trip to the Moon",
  description: "Georges Méliès creates the iconic silent film, launching a bullet-shaped rocket to the Moon in a whimsical scenario.",
  img: "/api/placeholder/100/100",
  people: ['Georges Méliès'],
  row: 9,
  connections: ['First Moon Landing'],
  category: "Sociocultural Factors"
},
{
  date: '1902',
  location: 'New Zealand',
  title: "Richard Pearse\'s Monoplane",
  description: "Richard Pearse builds a monoplane and makes brief, uncontrolled flights.",
  img: "/api/placeholder/100/100",
  people: ['Richard Pearse'],
  row: 9,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1903',
  location: 'Germany',
  title: "Karl Jatho\'s Powered Aircraft",
  description: "Karl Jatho builds an unstable monoplane that flies briefly but lacks thorough documentation.",
  img: "/api/placeholder/100/100",
  people: ['Karl Jatho'],
  row: 9,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
  {
  date: '1903',
  location: 'Scotland',
  title: "Preston Watson\'s Alleged Flight",
  description: "Preston Watson allegedly flies, though no strong evidence exists.",
  img: "/api/placeholder/100/100",
  people: ['Preston Watson'],
  row: 9,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1904',
  location: 'Germany',
  title: "Ludwig Prandtl’s Boundary-Layer Theory",
  description: "Prandtl’s insight that a thin layer of fluid near a surface governs most aerodynamic drag/energy loss was a milestone in modern fluid mechanics and airplane design.",
  img: "/api/placeholder/100/100",
  people: ['Ludwig Prandtl'],
  row: 9,
  connections: [],
  category: "Conceptual & Scientific Breakthroughs"
},
{
  date: '1906',
  location: 'Brazil/France',
  title: "Alberto Santos-Dumont\'s 14-bis Flight",
  description: "Alberto Santos-Dumont flies the 14-bis in Paris—the first powered airplane flight recognized by the Aéro-Club de France.",
  img: "/api/placeholder/100/100",
  people: ['Alberto Santos-Dumont'],
  row: 10,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1906',
  location: 'Germany/Russia',
  title: "Martin Wilhelm Kutta & Nikolai Zhukovsky’s Lift Theorem",
  description: "Established the relationship between circulation around an airfoil and the lift force—crucial for calculating wing performance in aircraft.",
  img: "/api/placeholder/100/100",
  people: ['Martin Wilhelm Kutta', 'Nikolai Zhukovsky'],
  row: 9,
  connections: [],
  category: "Conceptual & Scientific Breakthroughs"
},
{
  date: '1907',
  location: 'Romania',
  title: "Traian Vuia\'s Monoplane",
  description: "Traian Vuia designs a monoplane with wheels that takes off unaided but flies only short distances.",
  img: "/api/placeholder/100/100",
  people: ['Traian Vuia'],
  row: 10,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1908',
  location: 'France',
  title: "Aída de Acosta Pilots Santos-Dumont\'s Dirigible",
  description: "Aída de Acosta becomes the first woman to pilot an aircraft: Santos-Dumont\'s dirigible No. 9.",
  img: "/api/placeholder/100/100",
  people: ['Aída de Acosta', 'Alberto Santos-Dumont'],
  row: 10,
  connections: [],
  category: "Sociocultural Factors"
},
{
  date: '1908',
  location: 'England',
  title: "H.G. Wells\'s The War in the Air",
  description: "H.G. Wells\'s novel envisions how airplanes could revolutionize warfare, foreshadowing aerial battles of WWI.",
  img: "/api/placeholder/100/100",
  people: ['H.G. Wells'],
  row: 10,
  connections: [],
  category: "Sociocultural Factors"
},
{
  date: '1908',
  location: 'United Kingdom',
  title: "John William Dunne\'s warplanes",
  description: "Develops tailless aircraft designs with military applications.",
  img: "/api/placeholder/100/100",
  people: ['John William Dunne'],
  row: 11,
  connections: [],
  category: "Conceptual & Scientific Breakthroughs"
},
{
  date: '1909',
  location: 'France/England',
  title: 'Louis Blériot Crosses the English Channel',
  description: "Louis Blériot\'s successful Channel crossing proves the airplane\'s viability for transportation.",
  img: "/api/placeholder/100/100",
  people: ['Louis Blériot'],
  row: 11,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1910',
  location: 'Brazil',
  title: "Dimitri Sensaud de Lavaud\'s Flight in Latin America",
  description: "Dimitri Sensaud de Lavaud completes the first powered flight in Latin America.",
  img: "/api/placeholder/100/100",
  people: ['Dimitri Sensaud de Lavaud'],
  row: 11,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1910',
  location: 'France',
  title: "Henri Fabre\'s Seaplane Flight",
  description: "Henri Fabre achieves the first successful seaplane flight.",
  img: "/api/placeholder/100/100",
  people: ['Henri Fabre'],
  row: 12,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1911',
  location: 'United States',
  title: "Calbraith Perry Rodgers' Transcontinental Flight",
  description: "Calbraith Perry Rodgers completes the first transcontinental flight across the United States.",
  img: "/api/placeholder/100/100",
  people: ['Calbraith Perry Rodgers'],
  row: 12,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
    {
    date: '1914–1918',
    location: 'Europe/Worldwide',
    title: 'Military Demand in World War I',
    description: 'World War I massively accelerates aircraft innovation, with governments funding engine, aerodynamics, and materials research—much of which transfers to civilian aviation post-war.',
    img: '/api/placeholder/100/100',
    people: ['Various WWI Aircraft Pioneers'],
    category: 'Sociocultural Factors',
    connections: [],
    row: 12
  },
{
  date: '1918',
  location: 'France',
  title: "Henry Farman\'s Aircraft in World War I",
  description: "Henry Farman develops aircraft used in World War I, advancing military aviation.",
  img: "/api/placeholder/100/100",
  people: ['Henry Farman'],
  row: 12,
  connections: [],
  category: "Conceptual & Scientific Breakthroughs"
},
{
  date: '1910',
  location: 'Romania',
  title: "Henri Coandă\'s Coandă-1910",
  description: "Henri Coandă builds the Coandă-1910, possibly the first jet-propelled aircraft.",
  img: "/api/placeholder/100/100",
  people: ['Henri Coandă'],
  row: 13,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1914',
  location: 'United States',
  title: 'First Commercial Airline',
  description: "The St. Petersburg-Tampa Airboat Line starts commercial flights, pioneering airline service.",
  img: "/api/placeholder/100/100",
  people: ['Thomas Benoist', 'Percival Fansler'],
  row: 13,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1928',
  location: 'Germany',
  title: 'The Graf Zeppelin',
  description: "The LZ 127 Graf Zeppelin, a large passenger-carrying rigid airship, enters commercial service and demonstrates long-distance travel potential.",
  img: "/api/placeholder/100/100",
  people: ['Ferdinand von Zeppelin'],
  row: 14,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
{
  date: '1947',
  location: 'United States',
  title: 'Breaking the Sound Barrier',
  description: "Chuck Yeager pilots the Bell X-1 to become the first to break the sound barrier in level flight.",
  img: "/api/placeholder/100/100",
  people: ['Chuck Yeager'],
  row: 14,
  connections: [],
  category: "Engineering Experiments & Demonstrations"
},
      {
        date: '1969',
        location: 'United States',
        title: 'First Moon Landing',
        description: 'Neil Armstrong and Buzz Aldrin land on the Moon...',
        img: '/api/placeholder/100/100',
        people: ['Neil Armstrong', 'Buzz Aldrin'],
        row: 15,
        connections: [],
        category: "Engineering Experiments & Demonstrations"
      }
    ];
